In [1]:
import os
import glob
import pandas as pd
import numpy as np
from datetime import datetime
from pathlib import Path

In [2]:


DATA_RECOMENDATIONS = Path("data/recommendations")
DATA_SUGGESTIONS = Path("data/suggestions")

for p in (DATA_RECOMENDATIONS, DATA_SUGGESTIONS):
    p.mkdir(parents=True, exist_ok=True)

In [3]:
def latest_file_in_directory(directory=DATA_RECOMENDATIONS):
    latest_file = max(
        f for f in os.listdir(directory)
        if f.startswith("trade_suggestions_") and f.endswith(".csv")
    )
    return latest_file

In [11]:
latest_file = latest_file_in_directory(DATA_RECOMENDATIONS)
df_all = pd.read_csv(os.path.join(DATA_RECOMENDATIONS, latest_file))
df_all.shape

(300, 12)

In [13]:
df_all = df_all.rename(columns={"Unnamed: 0": "ticker"})
df_all.head()

,ticker,symbol,HotScore,TrendScore,regularMarketPrice,regularMarketChangePercent,VolumeSpike,averageDailyVolume3Month,MomentumScore,VolumeScore,VolatilityScore,marketCap
0,0,AAL,0.566667,0.093023,16.125,4.302815,0.238109,70078392.0,0.790698,0.620155,0.317829,1.066484e+10
1,1,AAOI,0.837201,0.641148,191.710,13.404321,0.989493,12738271.0,0.990431,0.677033,0.947368,1.538334e+10
2,2,ACAD,0.763736,0.592428,25.320,6.745365,4.149225,1610954.0,0.820000,0.919822,0.477778,4.335692e+09
3,3,ACIW,0.865152,0.833333,45.170,5.242310,1.877374,788839.0,0.931818,0.926768,0.656566,4.592053e+09
4,4,ACLS,0.797129,0.935407,191.415,6.270818,1.078202,690953.0,0.760766,0.755981,0.863636,5.882929e+09

In [17]:
df_outcome = (
    df_all[
        [
            "symbol",
            "HotScore",
            "TrendScore",
            "regularMarketPrice",
            "VolatilityScore",
        ]
    ]
    .sort_values(
        by=["HotScore", "regularMarketPrice"],
        ascending=[False, True]   # HotScore: highest first, Price: lowest first
    )
    .reset_index(drop=True)
)

df_outcome.head()

  symbol  HotScore  TrendScore  regularMarketPrice  VolatilityScore
0    DPC  0.982843    1.000000              45.785         0.914216
1    AYI  0.981740    0.965686             363.660         0.990196
2   LGND  0.981187    0.989899             279.440         0.941919
3   QURE  0.971893    0.789941              48.160         0.964497
4   ASND  0.964865    0.928747             260.470         0.963145

In [19]:
today = datetime.now().strftime("%Y%m%d")
out_file = DATA_SUGGESTIONS / f"trade_suggestions_{today}.csv"
df_outcome.to_csv(out_file, index=False)